Models/Train.cs
using System.ComponentModel.DataAnnotations;

namespace StoredProc_Latt.Models
{
    public class Train
    {
        [Key]
        public string Color { get; set; }
        public string Brand { get; set; }

        public string Fuel { get; set; }
        public int Price { get; set; }

    }
}

Controllers/TrainsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using StoredProc_Latt.Data;
using StoredProc_Latt.Models;
using System.Text;


namespace StoredProc.Controllers
{
    public class TrainController : Controller
    {
        public StoredProc_LattContext _context;
        public IConfiguration _config { get; }

        public TrainController
            (
            StoredProc_LattContext context,
            IConfiguration config
            )
        {
            _context = context;
            _config = config;

        }


        public IActionResult Index()
        {
            return View();
        }

        public IEnumerable<Train> SearchResult()
        {
            var result = _context.Train
                .FromSqlRaw<Train>("spSearchTrains")
                .ToList();

            return result;
        }

        [HttpGet]
        public IActionResult DynamicSQL()
        {
            string connectionStr = _config.GetConnectionString("DefaultConnection");

            using (SqlConnection con = new SqlConnection(connectionStr))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = con;
                cmd.CommandText = "dbo.spSearchTrains";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                List<Train> model = new List<Train>();
                while (sdr.Read())
                {
                    var details = new Train();
                    details.Color = sdr["Color"].ToString();
                    details.Brand = sdr["Brand"].ToString();
                    details.Fuel = sdr["Fuel"].ToString();
                    details.Price = Convert.ToInt32(sdr["Price"]);
                    model.Add(details);
                }
                return View(model);
            }
        }

        /// <summary>
        /// SearchPageWithoutDynamicSQL
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult DynamicSQL(string Color, string Brand, string Fuel, int Price)
        {
            string connectionStr = _config.GetConnectionString("DefaultConnection");

            using (SqlConnection con = new SqlConnection(connectionStr))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = con;
                cmd.CommandText = "dbo.spSearchTrains";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                if (Color != null)
                {
                    SqlParameter param_fn = new SqlParameter("@Color", Color);
                    cmd.Parameters.Add(param_fn);
                }
                if (Brand != null)
                {
                    SqlParameter param_ln = new SqlParameter("@Brand", Brand);
                    cmd.Parameters.Add(param_ln);
                }
                if (Fuel != null)
                {
                    SqlParameter param_g = new SqlParameter("@Fuel", Fuel);
                    cmd.Parameters.Add(param_g);
                }
                if (Price != 0)
                {
                    SqlParameter param_s = new SqlParameter("@Price", Price);
                    cmd.Parameters.Add(param_s);
                }
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                List<Train> model = new List<Train>();
                while (sdr.Read())
                {
                    var details = new Train();
                    details.Color = sdr["Color"].ToString();
                    details.Brand = sdr["Brand"].ToString();
                    details.Fuel = sdr["Fuel"].ToString();
                    details.Price = Convert.ToInt32(sdr["Price"]);
                    model.Add(details);
                }
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult SearchWithDynamics()
        {
            string connectionStr = _config.GetConnectionString("DefaultConnection");

            using (SqlConnection con = new SqlConnection(connectionStr))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = con;
                cmd.CommandText = "dbo.spSearchTrains";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                List<Train> model = new List<Train>();
                while (sdr.Read())
                {
                    var details = new Train();
                    details.Color = sdr["Color"].ToString();
                    details.Brand = sdr["Brand"].ToString();
                    details.Fuel = sdr["Fuel"].ToString();
                    details.Price = Convert.ToInt32(sdr["Price"]);
                    model.Add(details);
                }
                return View(model);
            }
        }

        [HttpPost]
        public IActionResult SearchWithDynamics(string Color, string Brand, string Fuel, int Price)
        {
            string connectionStr = _config.GetConnectionString("DefaultConnection");

            using (SqlConnection con = new SqlConnection(connectionStr))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = con;
                cmd.CommandText = "dbo.spSearchTrains";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                StringBuilder stringBuilder = new StringBuilder("Select * from Trains where 1 = 1");

                if (Color != null)
                {
                    stringBuilder.Append(" AND Color=@Color");
                    SqlParameter param_fn = new SqlParameter("@Color", Color);
                    cmd.Parameters.Add(param_fn);
                }
                if (Brand != null)
                {
                    stringBuilder.Append(" AND Brand=@Brand");
                    SqlParameter param_ln = new SqlParameter("@Brand", Brand);
                    cmd.Parameters.Add(param_ln);
                }
                if (Fuel != null)
                {
                    stringBuilder.Append(" AND Fuel=@Fuel");
                    SqlParameter param_g = new SqlParameter("@Fuel", Fuel);
                    cmd.Parameters.Add(param_g);
                }
                if (Price != 0)
                {
                    stringBuilder.Append(" AND Price=@Price");
                    SqlParameter param_s = new SqlParameter("@Price", Price);
                    cmd.Parameters.Add(param_s);
                }
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                List<Train> model = new List<Train>();
                while (sdr.Read())
                {
                    var details = new Train();
                    details.Color = sdr["Color"].ToString();
                    details.Brand = sdr["Brand"].ToString();
                    details.Fuel = sdr["Fuel"].ToString();
                    details.Price = Convert.ToInt32(sdr["Price"]);
                    model.Add(details);
                }
                return View(model);
            }
        }


        /// <summary>
        /// DynamicSQLInStoredProcedure
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult DynamicSQLInStoredProcedure()
        {
            string connectionStr = _config.GetConnectionString("DefaultConnection");

            using (SqlConnection con = new SqlConnection(connectionStr))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = con;
                cmd.CommandText = "dbo.spSearchTrainsGoodDynamicSQL";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                List<Train> model = new List<Train>();
                while (sdr.Read())
                {
                    var details = new Train();
                    details.Color = sdr["Color"].ToString();
                    details.Brand = sdr["Brand"].ToString();
                    details.Fuel = sdr["Fuel"].ToString();
                    details.Price = Convert.ToInt32(sdr["Price"]);
                    model.Add(details);
                }
                return View(model);
            }
        }


        /// <summary>
        /// DynamicSQLInStoredProcedure
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult DynamicSQLInStoredProcedure(string Color, string Brand, string Fuel, int Price)
        {
            string connectionStr = _config.GetConnectionString("DefaultConnection");

            using (SqlConnection con = new SqlConnection(connectionStr))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = con;
                cmd.CommandText = "dbo.spSearchTrainsGoodDynamicSQL";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                if (Color != null)
                {
                    SqlParameter param = new SqlParameter("@Color", Color);
                    cmd.Parameters.Add(param);
                }
                if (Brand != null)
                {
                    SqlParameter param = new SqlParameter("@Brand", Brand);
                    cmd.Parameters.Add(param);
                }
                if (Fuel != null)
                {
                    SqlParameter param = new SqlParameter("@Fuel", Fuel);
                    cmd.Parameters.Add(param);
                }
                if (Price != 0)
                {
                    SqlParameter param = new SqlParameter("@Price", Price);

Views/Train/DynamicSQL.cshtml
<body style="padding-top: 10px">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel-heading">
            <h3>Train Search Form</h3>
        </div>
        <form asp-controller="Train" asp-action="DynamicSQL">
            <div>
                <label for="color">Color</label>
                <br />
                <input type="text" name="Color" placeholder="Color" />
            </div>
            <br />
            <div>
                <label for="brand">Brand</label>
                <br />
                <input type="text" name="Brand" placeholder="Brand" />
            </div>
            <br />
            <div>
                <label for="fuel">Fuel</label>
                <br />
                <select name="fuel">
                    <option value="diesel">Diesel</option>
                    <option value="gasoline">Gasoline</option>
                </select>
            </div>
            <br />
            <div>
                <label for="price">Price</label>
                <br />
                <input type="number" name="Prce" placeholder="" />
            </div>
            <br />
            <input type="submit" value="sumbit" />
        </form>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Color</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Fuel</th>
                    <th scope="col">Price</th>
                </tr>
            <tbody>
                    @foreach (var Train in Model)
                    {
                    <tr>
                        <td>@Train.Color</td>
                        <td>@Train.Brand</td>
                        <td>@Train.Fuel</td>
                        <td>@Train.Price</td>
                    </tr>
                    }
            </tbody>
        </table>
    </div>
</body>

Views/Train/DynamicSQLInStoredProcedure.cshtml
<body style="padding-top: 10px">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel-heading">
            <h3>DynamicSQLInStoredProcedure</h3>
        </div>
        <form asp-controller="Train" asp-action="DynamicSQLInStoredProcedure">
            <div>
                <label for="color">Color</label>
                <br />
                <input type="text" name="color" placeholder="Color" />
            </div>
            <br />
            <div>
                <label for="brand">Brand</label>
                <br />
                <input type="text" name="brand" placeholder="Brand" />
            </div>
            <br />
            <div>
                <label for="fuel">Fuel</label>
                <br />
                <select name="fuel">
                    <option value="diesel">Diesel</option>
                    <option value="gasoline">Gasoline</option>
                </select>
            </div>
            <br />
            <div>
                <label for="price">DynamicSQLInStoredProcedure</label>
                <br />
                <input type="number" name="DynamicSQLInStoredProcedure" placeholder="DynamicSQLInStoredProcedure" />
            </div>
            <br />
            <input type="submit" value="SearchWithDynamics" />
        </form>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Color</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Fuel</th>
                    <th scope="col">Price</th>
                </tr>
            <tbody>
                    @foreach (var Train in Model)
                    {
                    <tr>
                        <td>@Train.Color</td>
                        <td>@Train.Brand</td>
                        <td>@Train.Fuel</td>
                        <td>@Train.Price</td>
                    </tr>
                    }
            </tbody>
        </table>
    </div>
</body>

Views/Train/Index.cshtml
<li class="">
    <a class="btn btn-danger" asp-controller="Train" asp-action="SearchResult">SearchResult</a>
</li>
<li class="">
    <a class="btn btn-danger" asp-controller="Train" asp-action="DynamicSQL">DynamicSQL</a>
</li>
<li class="">
    <a class="btn btn-danger" asp-controller="Train" asp-action="SearchWithDynamics">SearchWithDynamics</a>
</li>
<li class="">
    <a class="btn btn-danger" asp-controller="Train" asp-action="DynamicSQLInStoredProcedure">DynamicSQLInStoredProcedure</a>
</li>

Views/Train/SearchWithDynamics.cshtml
<body style="padding-top: 10px">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel-heading">
            <h3>Train Search Form With Dynamic</h3>
        </div>
        <form asp-controller="Train" asp-action="SearchWithDynamics">
            <div>
                <label for="color">Color</label>
                <br />
                <input type="text" name="color" placeholder="Color" />
            </div>
            <br />
            <div>
                <label for="brand">Brand</label>
                <br />
                <input type="text" name="brand" placeholder="Brand" />
            </div>
            <br />
            <div>
                <label for="fuel">Fuel</label>
                <br />
                <select name="fuel">
                    <option value="diesel">Diesel</option>
                    <option value="gasoline">Gasoline</option>
                </select>
            </div>
            <br />
            <div>
                <label for="price">SearchWithDynamics</label>
                <br />
                <input type="number" name="SearchWithDynamics" placeholder="SearchWithDynamics" />
            </div>
            <br />
            <input type="submit" value="SearchWithDynamics" />
        </form>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Color</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Fuel</th>
                    <th scope="col">Price</th>
                </tr>
            <tbody>
                    @foreach (var Train in Model)
                    {
                    <tr>
                        <td>@Train.Color</td>
                        <td>@Train.Brand</td>
                        <td>@Train.Fuel</td>
                        <td>@Train.Price</td>
                    </tr>
                    }
            </tbody>
        </table>
    </div>
</body>